### ISSUE TITLE
MIMOSA webpage error

### ISSUE THREAD

**Issue by natalie-melendez** [borenstein-lab/MIMOSA#3]
Hi!

I am currently running MIMOSA for several groups (all individually). My last group will not run correctly even though I formatted the files the same way as with my previous groups. I wanted to confirm if the MIMOSA webpage has a minimum of samples to run? The groups I'm running are from 4 different mice groups: healthy (n=10), tumor-implanted (n=10), short term treated (n=4) and long-term treated (n=6). I am having troubles with my short term treated  group (n=4). I appreciate any feedback! 

<img width="1306" alt="Screenshot 2024-12-03 at 1 30 56 PM" src="https://github.com/user-attachments/assets/31bc65e6-2c8d-414c-b5c3-254425f30e18">

**Comment by cnoecker** [comment]
Hi Natalie, 
Thanks for your message. Yes, the tool filters out any metabolites that have fewer than 5 nonzero samples, which in this case would be all of your metabolites (leading to the error you are seeing). This is a parameter that you can change if you are running the tool locally, but unfortunately can't be changed in the web app. In general, you're unlikely to get significant results with so few samples, so I would recommend grouping your samples into larger analysis sets - it shouldn't be a problem for the analysis to run more of your samples together since they are all generally the same sample type. By running them together, you might identify microbes that could be contributing to differences in metabolites, for example between the healthy and tumor groups. 
If you have other questions, could you open an issue. on the more recent MIMOSA2 repository here: https://github.com/borenstein-lab/mimosa2/ Thank you!

**Comment by natalie-melendez** [comment]
Hi @cnoecker,

Thank for clearing my doubts. I greatly appreciate it! Indeed my main goal is to be able to identify microbes that could be contributing to differences in metabolites between my experimental groups. However, since I am not able to upload a metadata file to the webpage to discriminate between groups I am unable to do so. I assume this is possible for the R package of MIMOSA2? I have tried downloading the R package, however its been giving me some issues. Thank you for pointing out the github repository for MIMOSA2! I opened an issue there for the error I am getting with the R package. 

Thank you for your input!
